Aida 466
NextCenturyCorporation/neon-dash pull request #124
Opened 2018-12-13 19:13 UTC by bdpham

Cherry-picked stable changes from verdi-demo branch.
Notable changes:
- Datatable ignoreself option now works with multi-filters
- Colorsets now have globalcolor mapping for specified fields (config colormaps)
- Thumbnail grid now has baseball card view
- Taxonomy viewer now shows node count

@ecurley-nextcentury @snorpet Can you test with your respective configs and data?

2018-12-13 23:30 UTC, gitnordt requested changes

2018-12-13 23:30 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +                let id = neonUtilities.deepFind(d, this.options.idField.columnName);
I believe the sourceIdField code needs to bve added since it is used to add the node counts. Otherwise, this function is just counting the categories and types.

2018-12-14 15:25 UTC, bdpham commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +                let id = neonUtilities.deepFind(d, this.options.idField.columnName);
I'm not quite sure what the sourceField code is and where I can find it. I cherry picked this from the AIDA-416 PR. Can you point me to where I need to look?

2018-12-14 16:36 UTC, eaciv commented
As I only had minor changes to this branch, I don't feel comfortable approving it. However, this branch worked for my TA1 layout. Let me know if you need anything further from me.

2018-12-17 15:40 UTC, ThomasSchellenbergNextCentury commented on src/app/components/visualization-injector/visualization-injector.component.ts
> +} from '../thumbnail-grid/thumbnail-details.component';
FYI You don't actually need to import these components here since they're not being used directly by the visualization-injector.

2018-12-17 15:44 UTC, ThomasSchellenbergNextCentury commented on src/app/components/visualization-injector/visualization-injector.component.spec.ts
> +} from '../thumbnail-grid/thumbnail-details.component';
FYI You don't actually need to import these components here since they're not being used directly by the visualization-injector.

2018-12-17 16:05 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    public extensionFields: any[];
The extensionFields aren't actually used anywhere.  If there's really not a use for them, you can just delete them.

2018-12-17 16:06 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +                //console.log(this.taxonomyGroups);
Remove unneeded comment

2018-12-17 16:10 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    handleFiltersChangedEvent($event): void {
So what's the goal of overriding this function?  Is it to update the visualization without requerying?

2018-12-17 16:17 UTC, bdpham commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    handleFiltersChangedEvent($event): void {
@snorpet Can you help answer this question?

2018-12-17 16:20 UTC, ThomasSchellenbergNextCentury commented on src/app/components/thumbnail-grid/thumbnail-details.component.ts
> +export class TitleThumbnailSubComponent {
Can we move the 3 subcomponents into their own separate files please?  If we've done the work to create 3 distinct classes, that indicates that we want the subcomponents to be able to exist independently, but they can't do it properly if they're all in the same file together!

2018-12-17 16:34 UTC, ThomasSchellenbergNextCentury commented
@bdpham I'm getting errors in the TaxonomyViewer tests for createQuery and getExportFields.

2018-12-19 21:08 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    handleFiltersChangedEvent($event): void {
@ThomasSchellenbergNextCentury  @bdpham I am using the handleFiltersChangedEvent to handle the filter changes in the taxonomy component. Requering is still occurring after my defined actions are executed. This is a special case so if you want to discuss in more detail, we can take it offline. I am simply using a method already being executed instead a creating a new method with repetitive functionality. A notable difference is that I changed the base-neon.component version to accept an event argument when necessary. I believe this will be a useful change and the argument is not required so it shouldn't affect other code.

2018-12-19 21:42 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    handleFiltersChangedEvent($event): void {
@snorpet Where are you requerying?  The original handleFiltersChangedEvent called executeQueryChain, but you're overriding that behavior.  ~~The only time this would trigger a query is if you call removeFilter~~, but it looks like that's not guaranteed to happen.  Edit:  I was wrong:  removeFilter is not querying at all.

2018-12-19 21:44 UTC, gitnordt commented on src/app/components/thumbnail-grid/thumbnail-details.component.ts
> +export class TitleThumbnailSubComponent {
This statement is inaccurate. These are meant to be sub-components of the thumbnail grid component. If the desire is to have these as independent components, putting their classes in separate files are not going to accomplish this. All components would have to be re-worked to accomplish the thumbnail grid functionality and styling. Afterwards, the thumbnail grid component would be deprecated because it wouldn't have a use anymore. In this case, the classes being housed in the same file does not have an impact on usability. This change request is personal preference, no exclamation needed.

2018-12-19 22:28 UTC, ThomasSchellenbergNextCentury commented on src/app/components/thumbnail-grid/thumbnail-details.component.ts
> +export class TitleThumbnailSubComponent {
@snorpet If they're all dependent on the thumbnail-grid, why bother separating them into 3 classes?  Why not just have 1 class with an ngIf on all 3 templates?  The main reason for having separate classes is if there's a chance we're going to reuse them independently (for example, import the Card into another widget, but not the Details or the Title).

2018-12-19 23:42 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    handleFiltersChangedEvent($event): void {
executeQueryChain is still being called after my code is executed. As I suggested before, we can take the conversation offline. It is not being overriden. If you are expecting JAVA-like override behavior, you may be disappointed. JavaScript override works a little differently due to inheritance from my understanding.

2018-12-19 23:45 UTC, gitnordt commented on src/app/components/thumbnail-grid/thumbnail-details.component.ts
> +export class TitleThumbnailSubComponent {
That is fine. If you would like me to change them to templates, please put in a ticket and assign it to me. This should not hold up Bao's PR as this is already code that was previously approved by you and pushed into the AIDA master branch.

2018-12-19 23:57 UTC, gitnordt requested changes
Bao, I noticed that one change is still missing from the taxonomyviewercomponent.html, line 122. This is the line that allows for the nodeCount to be displayed in the taxonomy.

<span (click)="onEvent($event, node)">{{ node.data.name }} <span *ngIf="node.data.nodeCount > 0">({{ node.data.nodeCount }})</span></span>

2018-12-20 18:30 UTC, ThomasSchellenbergNextCentury commented on src/app/components/thumbnail-grid/thumbnail-details.component.ts
> +export class TitleThumbnailSubComponent {
@bdpham Please add a (low priority) ticket for this.

2018-12-20 18:30 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +    handleFiltersChangedEvent($event): void {
@bdpham and I have held a discussion and he will be adding a ticket for any needed bug fixing.

2018-12-20 18:30 UTC, ThomasSchellenbergNextCentury approved these changes

2018-12-20 19:04 UTC, gitnordt approved these changes

2018-12-20 19:04 UTC, merged