Merging LORELEI and VMAP into AIDA / VERDI (Feb 2019)
NextCenturyCorporation/neon-dash pull request #154
Opened 2019-02-18 16:54 UTC by ThomasSchellenbergNextCentury

Stacey and / or Bao, can you please do a thorough test and verify that this code works with the AIDA / VERDI dashboards / datasets ?

2019-02-21 21:06 UTC, bdpham submitted a review, later dismissed
The network graph won't filter when a node is double clicked. The filter(s) are created but the graph doesn't seem to be affected by it. I believe this bug occurred from the last neon-wide merge and not this one. I think that this should be a separate task instead of being addressed in this PR. That being said, everything else seems to work fine on my end, so I will approve. Please wait on merging/closing this PR until after @snorpet has approved.

2019-02-22 15:52 UTC, ThomasSchellenbergNextCentury commented
@bdpham Concerning the filter bug:  This happens on verdi-master too.  I think the behavior was added intentionally.  Here's the relevant line:  https://github.com/NextCenturyCorporation/neon-dash-internal/blame/verdi-master/src/app/components/network-graph/network-graph.component.ts#L712

2019-02-22 16:23 UTC, eaciv commented
@bdpham, @ThomasSchellenbergNextCentury: Oof...this was caused by me? I introduced that condition to avoid entering code I didn't think it would need to with an empty result set. My code will work correctly if the "else if" condition is removed. Sorry for the inconvenience, guys.

2019-02-22 19:31 UTC, gitnordt requested changes

2019-02-22 19:31 UTC, gitnordt commented on src/app/components/query-bar/query-bar.component.ts
> +        return query;
Query Bar is no longer cleared out when all filters are removed. I'm not sure if this code caused the issue or if it was a prior merge. We may need to put a separate ticket in for this one.

2019-02-22 19:31 UTC, gitnordt commented on src/app/components/media-viewer/media-viewer.component.html
> +                        [class]="tab.selected.border ? ('video with-border border-mat-' + tab.selected.border) : 'video'">
AIDA has a recurring issue with youtube videos not showing up in the media viewer (referencing AIDA-235). The fix for this is to remove the video html tag as it can not handle youtube embed links. The iframe tag should be used to handle all videos instead. Unfortunately, even though I have removed the video tags and related code from the verdi-master repo multiple times, the code keeps getting merged back in causing the youtube links to break again. Please remove the video tags and related code.

2019-02-22 19:31 UTC, gitnordt commented on src/app/components/current-filters/current-filters.component.html
> +                    <mat-icon>delete</mat-icon>
I found an issue that is a little difficult to recreate, but I am getting some inconsistent behavior between the filters for the taxonomy and network graph. Sometimes deleting all filters does not reset the components.

One case where I seem to be able to recreate the issue: Go to the TA2 Dashboard. Click on a document to filter network graph, then double click on a node in the network graph to add additional filters. Then, remove the filters from the network graph(Not from the filter tray). The network graph is still filtered even though all filters have been removed.

I wasn't sure if this needed to be a separate bug or if it could be addressed in these changes.

2019-02-22 19:34 UTC, ThomasSchellenbergNextCentury commented on src/app/components/media-viewer/media-viewer.component.html
> +                        [class]="tab.selected.border ? ('video with-border border-mat-' + tab.selected.border) : 'video'">
@snorpet VMAP needs to be able to show videos.  Let's get together to talk about a collective solution.

2019-02-22 19:38 UTC, gitnordt requested changes

2019-02-22 19:38 UTC, gitnordt commented on src/app/components/map/map.component.html
>                          <mat-icon class="neon-icon-small" *ngIf="options.layers.length > 1" (click)="removeLayer(layer)">delete</mat-icon>
I am not sure if this is an AIDA-specific issue or if other projects are seeing this as well. I noticed that when clicking on the layers icon on the map, the menu contains a checkbox input with a label that says 'undefined'. 

I wasn't sure if this was a product of the merge or something that has been there.

2019-02-22 19:44 UTC, ThomasSchellenbergNextCentury commented on src/app/components/current-filters/current-filters.component.html
> +                    <mat-icon>delete</mat-icon>
I'm having trouble reproducing the issue, but it may be related to the bug that Bao found.  Let me implement the fix that Eddie recommended and you can try it again.

2019-02-22 21:01 UTC, ThomasSchellenbergNextCentury commented on src/app/components/query-bar/query-bar.component.ts
> +        return query;
It was definitely caused by a prior merge (I tested verdi-master).  I don't know of a quick-fix, so let's add a ticket for this in the backlog.  On a related note, maybe I'll be able to fix this in the filter changes I've been doing, but I don't want to guarantee anything right now :)

2019-02-22 21:01 UTC, ThomasSchellenbergNextCentury commented on src/app/components/map/map.component.html
>                          <mat-icon class="neon-icon-small" *ngIf="options.layers.length > 1" (click)="removeLayer(layer)">delete</mat-icon>
As we discussed earlier, let's worry about this later.  Who knows how long it's been there!

2019-02-22 22:06 UTC, gitnordt commented on src/app/components/map/map.component.html
>                          <mat-icon class="neon-icon-small" *ngIf="options.layers.length > 1" (click)="removeLayer(layer)">delete</mat-icon>
Put in a ticket for this issue so we can keep track, NEON-12

2019-02-22 22:14 UTC, gitnordt commented on src/app/components/query-bar/query-bar.component.ts
> +        return query;
Put in a ticket for this one, AIDA-560

2019-02-22 22:15 UTC, gitnordt submitted a review, later dismissed

2019-02-26 22:45 UTC, bdpham approved these changes
My requested change has been fixed. Approving.

2019-02-26 22:58 UTC, merged