Aida 410
NextCenturyCorporation/neon-dash pull request #156
Opened 2019-02-26 15:27 UTC by gitnordt

2019-02-26 22:19 UTC, ThomasSchellenbergNextCentury requested changes

2019-02-26 22:19 UTC, ThomasSchellenbergNextCentury commented on src/app/components/map/map.component.ts
> +                    this.replaceNeonFilter(this.options.layers[0], true, fieldObject, neonIdFilter);
We should call manageFieldFilters on each layer in `options.layers`, and the layer (used on lines 371 and 374) and `fieldsByLayer` (line 360) should be passed-in as a function argument (don't rely on index 0).

2019-02-26 23:09 UTC, gitnordt commented on src/app/components/map/map.component.ts
> +                    this.replaceNeonFilter(this.options.layers[0], true, fieldObject, neonIdFilter);
I added the fix for this. I hope it is what you are looking for. If not, I may need some more guidance. Thanks!

2019-02-28 15:52 UTC, ThomasSchellenbergNextCentury commented on src/app/components/map/map.component.ts
> +                    this.replaceNeonFilter(this.options.layers[0], true, fieldObject, neonIdFilter);
Looks good to me!

2019-02-28 16:10 UTC, ThomasSchellenbergNextCentury commented
FYI I merged master into the branch to resolve merge conflicts.

2019-02-28 16:10 UTC, ThomasSchellenbergNextCentury approved these changes

2019-02-28 21:38 UTC, bdpham approved these changes

2019-02-28 21:39 UTC, merged