THOR-305: Adding contributors to each widget
NextCenturyCorporation/neon-dash pull request #179
Opened 2019-04-03 19:29 UTC by rartiss55

I updated the following configs to include partners that contributed to the data displayed in the footer of each widget:
- Humanity Roads
- Transition Partner
- APAN

All logos needed for current contributors are in assets/images/contributor-logos.

ContributionDialogComponent was added to display detailed info for each contributor listed.

Full list of current contributors/logos are also attached to the original ticket in JIRA.

2019-04-03 19:33 UTC, rartiss55 commented on src/app/config/config.HumanityRoads.yaml
> +              contributionKeys:
For the config, if contributors are listed in the dashboard section (but no contributorKeys are specified on a widget), then all the contributors will be listed for each widget. contributorKeys are used when there are different contributors on a per widget basis (you can also specify an empty array of contributorKeys if no attribution is needed for a widget but is needed for others).

2019-04-03 19:36 UTC, rartiss55 commented on src/app/components/annotation-viewer/annotation-viewer.component.html
> +    <!-- need to account for footer only, contribution text only, or footer and contribution text together -->
For widgets that already had footers, had to combine contributor text with existing footer (if applicable) since I can't have more than footer.

2019-04-03 19:36 UTC, rartiss55 commented on src/app/components/annotation-viewer/annotation-viewer.component.scss
Took this out to fix an existing formatting bug with annotation-viewer that was blocking me.

2019-04-04 22:23 UTC, Konnoke submitted a review, later dismissed
Thanks for fixing the annotation viewer html!

2019-04-10 11:55 UTC, ThomasSchellenbergNextCentury commented on src/app/components/base-neon-component/base-neon.component.ts
> +            return true;
This can just be
```
return ((this.options.contributionKeys && this.options.contributionKeys.length !== 0)
            || (this.options.contributionKeys === null
            && this.datasetService.getCurrentDashboard()
            && this.datasetService.getCurrentDashboard().contributors
            && Object.keys(this.datasetService.getCurrentDashboard().contributors).length));
```

2019-04-10 11:59 UTC, ThomasSchellenbergNextCentury commented on src/app/components/base-neon-component/base-neon.component.ts
> +        }
FYI You don't have to change this, but you could replace the `for` loop here with `filter` and `map`.  (I'm not sure if you'd consider it "cleaner" or "simpler", but I thought I'd mention it just in case.)
```
let contributors = contributorKeys.filter((key) => !!allContributors[key]).map((key) => allContributors[key]);
```
You could also return the result itself rather than saving it in a local variable.

2019-04-10 12:16 UTC, ThomasSchellenbergNextCentury commented
@rartiss55 Please add a few unit tests for the new contributor functions in the BaseNeonComponent.

2019-04-10 12:16 UTC, ThomasSchellenbergNextCentury commented
I don't like how we're saving program-specific logos in the repo, but I don't have an alternative suggestion right now.  I've made a ticket so we can think about it later:  https://nextcentury.atlassian.net/browse/THOR-1116

2019-04-10 12:18 UTC, ThomasSchellenbergNextCentury requested changes
Apparently I have to leave a comment to "Request changes" on a PR now.  Please see my previous comments.

2019-04-11 18:20 UTC, rartiss55 commented
@ThomasSchellenbergNextCentury I have made the requested changes. Please re-review.

2019-04-15 14:44 UTC, ThomasSchellenbergNextCentury submitted a review, later dismissed

2019-04-15 14:54 UTC, ThomasSchellenbergNextCentury approved these changes

2019-04-15 14:54 UTC, merged