Thor 501
NextCenturyCorporation/neon-dash pull request #180
Opened 2019-04-04 18:34 UTC by Konnoke

**THOR-501:** 
Add "no data" message to charts and page.
This is for when user has filtered chart to point where there is no data to display.

**What's new:**
- Data Message Component that shows an icon and text
- Added new functions and fields to baseNeonComponent to detect when there's no active data after filtering. 
- Added a new function toggleBodyContainer in baseNeonComponent that is override in the aggregation component so it can hide the body container when it's showing the Data Message Component.
- Added Data Message Component to Aggregation, Media Viewer, and Textcloud.
- Updated unit tests

**Attempted but not included because of issues:**
Tried adding more comprehensive tests by making a TestBaseNeonComponentMock class that extends TestBaseNeonComponent but uses the mock services in order to test the behaviors when filters are added or removed.

![image](https://user-images.githubusercontent.com/7284296/55579093-7f045280-56e5-11e9-9843-78543c7a20b1.png)

2019-04-10 17:51 UTC, ThomasSchellenbergNextCentury commented on src/app/components/base-neon-component/base-neon.component.ts
> +            }
FYI You don't have to change this, but this could be handled in fewer lines:
```
this.showNoData = !activeData || !activeData.data || !activeData.data.length;
```

2019-04-10 17:52 UTC, ThomasSchellenbergNextCentury commented on src/app/components/aggregation/aggregation.component.ts
> +        }
FYI You don't have to change this, but this could be handled in fewer lines:
```
bodyContainer.setAttribute('style', 'display: ' + (this.showNoData ? 'none' : 'show'));
```

2019-04-10 17:54 UTC, ThomasSchellenbergNextCentury commented on src/app/components/base-neon-component/base-neon.component.ts
> +        //Will be override in the aggregation component
You shouldn't name specific subclasses like this in override-able functions in a superclass:  you never know when you will create a new subclass that needs to override the same function, and then the comment will be stale.

2019-04-10 17:55 UTC, ThomasSchellenbergNextCentury commented on src/app/components/data-message/data-message.component.ts
> +    public currentVisualization: any;
It doesn't look like these three variables (`chartsAndGraph`, `visualizations`, and `currentVisualization`) are used anywhere.  If that's really the case, please remove them.

2019-04-10 17:56 UTC, ThomasSchellenbergNextCentury commented
It seems like the "No Data" message would be useful in other visualizations like the Document Viewer, Network Graph, News Feed, or Thumbnail Grid.  Should we add it to them too, or is that outside the scope of this task?

2019-04-10 18:02 UTC, ThomasSchellenbergNextCentury commented
I fixed an issue I found (an existing bug, unrelated to anything you did!) so the aggregation component would clear its legend properly.

2019-04-10 18:04 UTC, ThomasSchellenbergNextCentury requested changes
Please review my previous comments.

2019-04-10 21:19 UTC, Konnoke commented
> It seems like the "No Data" message would be useful in other visualizations like the Document Viewer, Network Graph, News Feed, or Thumbnail Grid. Should we add it to them too, or is that outside the scope of this task?

Yep, that's currently outside the scope of the ticket. The ticket only mentioned "charts and page" which Sophie clarified to mean only the aggregation, media viewer, and text cloud.

2019-04-10 21:39 UTC, ThomasSchellenbergNextCentury commented
OK, cool.  I created a new ticket to cover the other visualizations:  https://nextcentury.atlassian.net/browse/THOR-1117

2019-04-10 21:40 UTC, ThomasSchellenbergNextCentury commented on src/app/components/data-table/data-table.component.spec.ts
> +import { DataMessageComponent } from '../data-message/data-message.component';
You don't need the import here since it's not used in the Data Table.

2019-04-10 23:01 UTC, Konnoke commented on src/app/components/data-table/data-table.component.spec.ts
> +import { DataMessageComponent } from '../data-message/data-message.component';
Nice catch! I forgot to remove that.
I initially had it in the data table but I removed it because it was redundant. Ngx-datatable had its own message for no data.

2019-04-15 14:42 UTC, ThomasSchellenbergNextCentury approved these changes

2019-04-15 14:42 UTC, merged