Aida 627
NextCenturyCorporation/neon-dash pull request #185
Opened 2019-04-18 19:41 UTC by gitnordt

Implemented the ability to add and filter by an additional field in the timeline. This allows for cross-component filtering on multiple fields. These changes are dependent upon the most recent changes to the Neon Server code ([NextCenturyCorporation/neon-server](https://portal.nextcentury.com/owncloud/index.php/s/lRpjvIBXmfszWuz)). You will need to deploy the new Neon Server war file, before testing this PR.

2019-04-19 19:11 UTC, bdpham requested changes
Tests are failing:
ReferenceError: d3 is not defined

2019-04-19 19:14 UTC, gitnordt commented
> Tests are failing:
> ReferenceError: d3 is not defined

Added d3 import back in, it got removed when I was cleaning up my code. Sorry.

2019-04-22 17:52 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/timeline.component.ts
> +                        .filter((value, index, array) => array.indexOf(value) === index);
This `filter` is to remove duplicate values in `previousItem.filters`, right?

2019-04-23 12:04 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/TimelineSelectorChart.ts
> +                        if (data.date >= this.data.extent[0] && data.date <= this.data.extent[1]) {
I think there's a bug here:  the `<=` should be a `<`.

As we've discussed before, the timeline's filter is inclusive on the start date but exclusive on the end date (`>= startDate` and `< endDate`).

I noticed that, whenever you filter, the ID filters (or whatever is marked as the `filterField`) are including data that belongs to an extra bar in the timeline.  For example, if you filter the date on a single bar, it filter the IDs on both that bar AND the bar directly to its right.  Tracing through the code, it looks like the `onTimelineSelection` function was being sent too much `selectedData`, and changing the `<=` to a `<` seemed to fix the issue.

Let me know if my understanding is mistaken or if this solution has unexpected side-effects.

2019-04-23 14:55 UTC, gitnordt commented on src/app/components/timeline/timeline.component.ts
> +                        .filter((value, index, array) => array.indexOf(value) === index);
That is correct.

2019-04-23 14:57 UTC, gitnordt commented on src/app/components/timeline/TimelineSelectorChart.ts
> +                        if (data.date >= this.data.extent[0] && data.date <= this.data.extent[1]) {
Thank you for catching this. I change it in one part of the code, but did not make the change here.

2019-04-23 17:32 UTC, ThomasSchellenbergNextCentury submitted a review, later dismissed

2019-04-24 14:54 UTC, bdpham reviewed
There are a few filtering bugs that I notice. @snorpet and I have discussed this and will be working to get them fixed.

2019-04-24 15:50 UTC, gitnordt commented
> There are a few filtering bugs that I notice. @snorpet and I have discussed this and will be working to get them fixed.

I had a difficult time recreating the bug that Bao found. I had to change the granularity to day first, but it looks like if you select a part of the timeline that does not have a bar and then select a part of the timeline that does have a bar, the added filter field value no longer updates. I was able to confirm this in the active filters. I need to figure out how to capture the values for the filter field after an empty selection is made. I will work on the solution and update the code.

2019-04-24 18:48 UTC, gitnordt commented
> > There are a few filtering bugs that I notice. @snorpet and I have discussed this and will be working to get them fixed.
> 
> I had a difficult time recreating the bug that Bao found. I had to change the granularity to day first, but it looks like if you select a part of the timeline that does not have a bar and then select a part of the timeline that does have a bar, the added filter field value no longer updates. I was able to confirm this in the active filters. I need to figure out how to capture the values for the filter field after an empty selection is made. I will work on the solution and update the code.

The issue was that once there was a selection on the timeline that returned no data, there was a filter created without a whereClause. This posed a problem when trying to locate/replace the filter since it did not include a whereClause associated with the filterField. After speaking with Thomas, we found that the best way to approach this issue is to create a filter with a whereClause that sets the filterField equal to an empty string. That way it can be located by the whereClause (lhs) and replaced as needed. 

Filtering should work as expected now. When a selection on the timeline returns no data, all other components associated with that filter field should be cleared.

2019-04-24 21:02 UTC, bdpham submitted a review, later dismissed

2019-04-25 14:29 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/timeline.component.ts
> +                this.manageFieldFilters(setFilter, neonFilters, false);
The indentation on lines 221-228 looks like it got messed up.

2019-04-25 14:33 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/timeline.component.ts
> +            clauses.push(neon.query.where(filterField, '=', ''));
Could you please add a comment here that the "filter on field equals empty string" behavior might not work as expected with every dataset (basically what we discussed yesterday)?  You can mention ticket NEON-36 too.

2019-04-25 16:54 UTC, gitnordt commented on src/app/components/timeline/timeline.component.ts
> +                this.manageFieldFilters(setFilter, neonFilters, false);
Done

2019-04-25 16:54 UTC, gitnordt commented on src/app/components/timeline/timeline.component.ts
> +            clauses.push(neon.query.where(filterField, '=', ''));
Done

2019-04-25 17:43 UTC, bdpham approved these changes

2019-04-25 17:45 UTC, ThomasSchellenbergNextCentury approved these changes

2019-04-25 17:55 UTC, merged