THOR-942 Filter Refactor (Aggregation Component)
NextCenturyCorporation/neon-dash pull request #186
Opened 2019-04-19 11:40 UTC by ThomasSchellenbergNextCentury

WHAT DOES THOR-942 WANT TO FIX
- Each filterable visualization component creates and maintains a list of its own filter objects (with unique and inconsistent structure) and overrides many superclass functions (getCloseableFilters, getFiltersToIgnore, getFilterText, removeFilters, setupFilters, etc.) to manage its filters.
- The visualization components depend on the neon.query library, making it impossible to use them independently of the Neon Middleware.
- Filters are no longer saved in the server (due to a previous ticket) and thus we can remove the complex callback chains from the  functions that add/delete filters.
- A lot of code to create, add, or toggle filters in the visualization components is duplicated across the codebase.
- The setupFilters function, intended to allow filters on the same field to be shared across visualizations, is clumsy, confusing, and usually implemented incorrectly (or not implemented at all).
- The visualization components show little grey boxes when filtered, and we don't want to show the boxes anymore.

HOW DOES THOR-942 FIX IT
- Created a set of interfaces in the FilterService to represent filters across the application.  We're using interfaces because they are equivalent to JSON objects and are thus compatible with future non-Typescript Web Components.  The FilterDesign interfaces are converted to Filter classes that are used internally within the FilterService.
- Replaced the many abstract filter functions in BaseNeonComponent with a single function:  designEachFilterWithNoValues.  This function allows the visualization to inform the BaseNeonComponent as to the types of filters that are compatible with it as well as a callback function to redraw its filters whenever updated.  Filters are now automatically shared across visualizations by using the output from designEachFilterWithNoValues (no need to implement setupFilters in each visualization!).
- Replaced the addFilter, removeFilter, and replaceFilter functions with deleteFilters, exchangeFilters, and toggleFilters that take FilterDesigns (JSON objects) rather that neon.query objects.
- Replaced the unique filters from the individual visualization components with a cachedFilters property in the BaseNeonComponent that copies filters from the FilterService rather than using separate (unique, inconsistent) filter objects.
- The FilterService now saves each filter not by visualization but by unique database/table/field/operator (FilterDataSource).  This way a filter can easily be shared across visualizations based on its FilterDataSource.  Filters themselves are now tied to the whole application rather than a single visualization.
- Removed the little grey boxes from the visualizations.

WHAT IS IN THIS PR
- Updates to the Aggregation Component to make it work with the new FilterService and BaseNeonComponent changes.
- I combined the select and deselect functions in the Aggregation Subcomponents.
- I replaced the need to override handleClickEvent and handleHoverEvent with a selectMode property in the Aggregation Subcomponents.
- I moved a lot of the complex select/deselect behavior to other tickets and left TODOs with the ticket names.

To test this commit, please use branch THOR-942-services because that has the complete, functional set of changes.

2019-04-24 18:25 UTC, Konnoke approved these changes

2019-04-24 18:25 UTC, Konnoke commented on src/app/components/aggregation/aggregation.component.html
> +    <div class="filter-container" *ngIf="showLegend()">
I agree with moving the ngif from the app-legend to the div element because it would persist the legend component instead of creating and destroying the legend component each time but are there other benefits?

2019-04-24 21:10 UTC, rartiss55 commented on src/app/components/aggregation/aggregation.component.html
> -
It looks like space for the contribution footer (THOR-305) is still being made for the aggregation component, but that the display logic here was removed. I also noticed the space/contribution text disappeared completely from the data table. Please put this logic back in for components that it was removed from (should appear if needed for all components). Various LORELEI configs you can use to test include:
- TransitionPartner
- APAN
- HumanityRoads

2019-04-25 16:49 UTC, rartiss55 requested changes
See earlier comment.

2019-04-25 17:49 UTC, ThomasSchellenbergNextCentury commented on src/app/components/aggregation/aggregation.component.html
> +    <div class="filter-container" *ngIf="showLegend()">
This change wasn't as witty as you might think.  Previously, the "filter-container" contained both the legend and the gray filter boxes.  The showHeaderContainer function returned whether either of those needed to be visible.  By removing the gray filter boxes, the only thing that needs to be shown is the legend, so I replaced showHeaderContainer with showLegend.  Does that answer your question?

2019-04-25 17:50 UTC, ThomasSchellenbergNextCentury commented on src/app/components/aggregation/aggregation.component.html
> -
Ugh, OK, I thought I had merged it in correctly, but obviously I messed something up.  I'll fix the aggregation component and data table, and I'll also check the other components to make sure they have the contribution footers too.

2019-04-26 20:45 UTC, rartiss55 approved these changes

2019-05-18 02:43 UTC, closed without merging