THOR-942 Filter Refactor (Query Bar and Taxonomy)
NextCenturyCorporation/neon-dash pull request #188
Opened 2019-04-19 11:57 UTC by ThomasSchellenbergNextCentury

WHAT DOES THOR-942 WANT TO FIX
- Each filterable visualization component creates and maintains a list of its own filter objects (with unique and inconsistent structure) and overrides many superclass functions (getCloseableFilters, getFiltersToIgnore, getFilterText, removeFilters, setupFilters, etc.) to manage its filters.
- The visualization components depend on the neon.query library, making it impossible to use them independently of the Neon Middleware.
- Filters are no longer saved in the server (due to a previous ticket) and thus we can remove the complex callback chains from the  functions that add/delete filters.
- A lot of code to create, add, or toggle filters in the visualization components is duplicated across the codebase.
- The setupFilters function, intended to allow filters on the same field to be shared across visualizations, is clumsy, confusing, and usually implemented incorrectly (or not implemented at all).
- The visualization components show little grey boxes when filtered, and we don't want to show the boxes anymore.

HOW DOES THOR-942 FIX IT
- Created a set of interfaces in the FilterService to represent filters across the application.  We're using interfaces because they are equivalent to JSON objects and are thus compatible with future non-Typescript Web Components.  The FilterDesign interfaces are converted to Filter classes that are used internally within the FilterService.
- Replaced the many abstract filter functions in BaseNeonComponent with a single function:  designEachFilterWithNoValues.  This function allows the visualization to inform the BaseNeonComponent as to the types of filters that are compatible with it as well as a callback function to redraw its filters whenever updated.  Filters are now automatically shared across visualizations by using the output from designEachFilterWithNoValues (no need to implement setupFilters in each visualization!).
- Replaced the addFilter, removeFilter, and replaceFilter functions with deleteFilters, exchangeFilters, and toggleFilters that take FilterDesigns (JSON objects) rather that neon.query objects.
- Replaced the unique filters from the individual visualization components with a cachedFilters property in the BaseNeonComponent that copies filters from the FilterService rather than using separate (unique, inconsistent) filter objects.
- The FilterService now saves each filter not by visualization but by unique database/table/field/operator (FilterDataSource).  This way a filter can easily be shared across visualizations based on its FilterDataSource.  Filters themselves are now tied to the whole application rather than a single visualization.
- Removed the little grey boxes from the visualizations.

WHAT IS IN THIS PR
- Updates to the Query Bar and Taxonomy Viewer Components to make them work with the new FilterService and BaseNeonComponent changes.
- I made a big change in how the Taxonomy specifically creates filters:  rather than adding or removing filters on individual unchecked/checked nodes and their children/parents, it now completely replaces its previous filters with new filters representing ALL unchecked nodes (and their children/parents) whenever a node is unchecked/checked.  I think I tested this new behavior pretty well, but, Stacey, I want to get your feedback to make sure I haven't made any mistakes!

To test this commit, please use branch THOR-942-services because that has the complete, functional set of changes.

2019-05-08 17:28 UTC, gitnordt requested changes

2019-05-08 17:28 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        this.exchangeFilters([categoryFilter, typeFilter, subTypeFilter].filter((filter) => !!filter), filterDesignListToDelete);
The taxonomy checkbox behavior: 

- When all child nodes are checked, the parent should also be checked. 

- When a parent node has at least one child that is indeterminate, the parent should also be indeterminate

- When a child node is unchecked in the taxonomy and it is the only child or all of its siblings are unchecked, it is expected that the parent node is unchecked. 

- When a child node is unchecked and it has siblings that are checked, it is expected that the parent node is indeterminate (-).  

updateChildNodesCheckbox and updateParentNodesCheckBox are the methods responsible for this functionality. However, it looks like they may be getting overriden by a call to refreshVisualization in base-neon.component.  I am seeing the parent node change to indeterminate and then, shortly after, change to checked. Putting the update checkbox methods after the exchangeFilters call may fix the issue, but I'm not certain.

2019-05-08 17:28 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        // Find all the unselected groups in the taxonomy (parents and children).
I am seeing a strange one-off bug. When using AIDA data for the taxonomy, if you open the first category which is ENTITY and uncheck the GeneralAffiliation child node, you can never check it again. None of the other categories have this problem from what I can see. I think it is safe to say it is specific to the first subType object created.

2019-05-08 17:32 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        }
Do you have an ETA on when we can expect filtering for the sourceIdField to be implemented? I ask because we did have a user point out that filtering was not working for documents in the taxonomy view.

2019-05-08 17:57 UTC, gitnordt requested changes

2019-05-08 17:57 UTC, gitnordt commented on src/app/components/query-bar/query-bar.component.ts
> +            let values: any[] = this.queryArray.filter((value) =>
I am not getting any values for this.queryArray. I am seeing the following error in the console:

QueryBarComponent.html:6 ERROR TypeError: Cannot read property 'filter' of undefined
    at QueryBarComponent.push../src/app/components/query-bar/query-bar.component.ts.QueryBarComponent.createFilter (query-bar.component.ts:327)
    at Object.eval [as handleEvent] (QueryBarComponent.html:7)
    at handleEvent (core.js:21652)
    at callWithDebugContext (core.js:22746)
    at Object.debugHandleEvent [as handleEvent] (core.js:22449)
    at dispatchEvent (core.js:19101)
    at core.js:19548
    at HTMLInputElement.<anonymous> (platform-browser.js:993)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:16126)

2019-05-08 21:14 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        }
This is what Scott's working on right now (https://nextcentury.atlassian.net/browse/NEON-22).  It really depends on how quickly he can get the first part done (the server-specific part), and then how quickly we can integrate it with the rest of the system (at least that can be divided among multiple people).  I'd say 2-4 weeks, but that's a rough guess.  Does that help, at least?

2019-05-09 19:45 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        this.exchangeFilters([categoryFilter, typeFilter, subTypeFilter].filter((filter) => !!filter), filterDesignListToDelete);
Great catch!  I was able to reproduce your issue.

I think this was not happening previously because the taxonomyViewer usually sets ignoreSelf to true.  However, there was a bug in the BaseNeonComponent causing the taxonomyViewer to requery itself (and thus call refreshVisualization) even when ignoreSelf equals true.  I've fixed the bug and can confirm that the behaviors you want actually happen now.

Side note:  Is there ever a situation in which we'd want ignoreSelf to be false for the taxonomyViewer?  If not, the taxonomyViewer can override the shouldFilterSelf function to always return false.  That might be useful so that this same problem doesn't occur if we forget to set ignoreSelf to true on the taxonomyViewer.

2019-05-09 19:59 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        // Find all the unselected groups in the taxonomy (parents and children).
I was able to reproduce this issue.  However, it must have also been caused by the calls to refreshVisualization, because my solution to your previous comment also solved this issue too.  Yay!

2019-05-09 20:31 UTC, ThomasSchellenbergNextCentury commented on src/app/components/query-bar/query-bar.component.ts
> +            let values: any[] = this.queryArray.filter((value) =>
Wow, how did I let THAT slip past me?!  My bad.

Looks like initializing the queryArray fixes the issue.

Side note:  I found some funny behavior with the extensions filters that I think (maybe) is a config issue.  I'll stop by tomorrow to talk to you about it.

2019-05-09 20:33 UTC, ThomasSchellenbergNextCentury commented
@snorpet The bug fixes to your comments above are on the THOR-942-services branch here:  https://github.com/NextCenturyCorporation/neon-dash-internal/commit/05a5d213983102be15d2447eab1acfce921176bf

2019-05-10 14:28 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +        this.exchangeFilters([categoryFilter, typeFilter, subTypeFilter].filter((filter) => !!filter), filterDesignListToDelete);
I don't believe there is a circumstance where we would want ignoreSelf to be false. That would mean that as you check boxes, values in the taxonomy would be filtered out. I think that would be very confusing for the user.

2019-05-10 15:43 UTC, gitnordt commented on src/app/components/query-bar/query-bar.component.ts
> +            let values: any[] = this.queryArray.filter((value) =>
Just wondering are the pre-populated query values coming up for you as you start to type a question in the query bar? 

I am getting a different error in the console now:

ERROR TypeError: Cannot read property 'datastore' of null
    at Object.isSimpleFilterDesign (filter.service.ts:212)
    at Object.createFilterDataSourceListFromDesign (filter.service.ts:114)
    at SingleListFilterCollection.push../src/app/services/filter.service.ts.AbstractFilterCollection.findFilterDataSources (filter.service.ts:237)
    at filter.service.ts:918
    at Array.forEach (<anonymous>)
    at FilterService.push../src/app/services/filter.service.ts.FilterService.updateCollectionWithGlobalCompatibleFilters (filter.service.ts:916)
    at QueryBarComponent.push../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.updateCollectionWithGlobalCompatibleFilters (base-neon.component.ts:790)
    at QueryBarComponent.push../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.ngOnInit (base-neon.component.ts:174)
    at checkAndUpdateDirectiveInline (core.js:20644)
    at checkAndUpdateNodeInline (core.js:21908)

2019-05-10 15:47 UTC, gitnordt requested changes
I'm still having issues with the query bar.

2019-05-13 13:25 UTC, ThomasSchellenbergNextCentury commented on src/app/components/query-bar/query-bar.component.ts
> +            let values: any[] = this.queryArray.filter((value) =>
@snorpet The extensionFields bindings for the queryBar in your configFile are incorrect, assuming that this is your config file:  https://github.com/NextCenturyCorporation/neon-dash-internal/blob/verdi-master/src/app/config/config.verdi-ta2-ta3.yaml#L647

The extensionFields format is the same as before; it doesn't use table keys or field keys.  Since the extensionFields are a custom binding defined by the Query Bar, the changes that affected the other fields don't affect it, so someone would need to change the custom code in the Query Bar to update it to use table keys and field keys.

Keep it like this:
```
extensionFields:
  - database: verdi-support
    table: hypothesis_info
    idField: hypothesis_id
    filterField: query
  - database: kb-simple
    table: seedling
    idField: docIds
    filterField: hypotheses
```

2019-05-13 13:30 UTC, ThomasSchellenbergNextCentury commented on src/app/components/query-bar/query-bar.component.ts
> +            let values: any[] = this.queryArray.filter((value) =>
Also:  I think I fixed my issue from before.  Please pull the latest code from THOR-942-services.

https://github.com/NextCenturyCorporation/neon-dash-internal/commit/f9f5bfa04e3e1ba7815f0f2483dda4b68b5ba188

2019-05-14 15:28 UTC, gitnordt commented on src/app/components/query-bar/query-bar.component.ts
> +            let values: any[] = this.queryArray.filter((value) =>
Thank you, I will try testing with these extensionField values.

2019-05-17 19:39 UTC, gitnordt approved these changes

2019-05-17 19:40 UTC, merged