THOR-1043 Non-Primitive Options
NextCenturyCorporation/neon-dash pull request #206
Opened 2019-05-10 17:56 UTC by arciisine

Everything should be up and running, and app tests have been resolved.

2019-05-13 17:39 UTC, ThomasSchellenbergNextCentury commented on src/app/components/options-list/options-list.component.html
> +                }
Would these options be better saved as a variable in the .ts file?

2019-05-13 17:42 UTC, ThomasSchellenbergNextCentury commented on src/app/widget-option.spec.ts
> +`;
The indentation here annoys me, but I understand why it is necessary.  Is there a commonly-accepted standard for dealing with situations like this?  Would it be "cleaner" to use `\n` instead?

2019-05-13 17:44 UTC, ThomasSchellenbergNextCentury commented on src/app/widget-option.spec.ts
> +describe('NonPrimitive Fields', () => {
I think you should add a test on setting `intermediateValue` to an improperly-formatted string and checking that it returns `undefined`.

2019-05-13 17:46 UTC, ThomasSchellenbergNextCentury commented on src/app/widget-option.ts
> +    private _intermediateValue: string;
I like the `_intermediateValue` here.  I've added a note that we could likely use this strategy on validating numbers in the future too:  https://nextcentury.atlassian.net/browse/THOR-1044

2019-05-13 17:46 UTC, ThomasSchellenbergNextCentury requested changes
Please see specific comments for details.

2019-05-13 22:14 UTC, arciisine commented on src/app/components/options-list/options-list.component.html
> +                }
Potentially, they are intimately tied to the component.  I view them akin to html attributes, vs external config.

2019-05-13 22:16 UTC, arciisine commented on src/app/widget-option.spec.ts
> +`;
Yaml will consume all the leading spaces of equal width, it just may not be apparent that is happening when comparing the values.  We could also build a function to strip the leading spaces consistently.

2019-05-13 22:16 UTC, arciisine commented on src/app/widget-option.spec.ts
> +describe('NonPrimitive Fields', () => {
Sure, will add.

2019-05-14 16:09 UTC, arciisine commented on src/app/widget-option.spec.ts
> +`;
Relied on yaml stripping indentation

2019-05-14 16:12 UTC, ThomasSchellenbergNextCentury approved these changes

2019-05-14 22:15 UTC, rartiss55 approved these changes

2019-05-15 00:29 UTC, Konnoke approved these changes

2019-05-15 14:28 UTC, merged