THOR-1152 Streaming Data Notifications (THOR-1183,1184,1185)
NextCenturyCorporation/neon-dash pull request #211
Opened 2019-05-16 21:46 UTC by arciisine

Providing groundwork for streaming data changes:

THOR-1184 - Remove Old RequeryInterval Code from Neon UI 
THOR-1185 - Create Streaming Data Notification Component, currently just a button on the appcomponent
THOR-1183 - Receive Messages in the UI from the Server (UI Task)

2019-05-16 23:00 UTC, ThomasSchellenbergNextCentury commented on src/app/app.component.ts
> +        fromEvent(new EventSource('/neon/services/dataset/listen'), 'message').subscribe((time) => this.dataAvailableDashboard());
Hmm, OK, so, I think the we made an assumption when we wrote the ticket, and part of the task wasn't properly communicated:

The events need to be handled in the Neon Middleware.  Please move the EventSource and the hard-coded path (`/neon/services/dataset/listen`) to a function there, probably in the Connection object, and refer to that function here.  The function can take a custom callback (`dataAvailableDashboard`, or whatever).

I've updated the `lorelei-master` to import the Neon Middleware from its GitHub repo (Eric had accidentally committed it to `master`).

You can make the changes branching off from `master`:  https://github.com/NextCenturyCorporation/neon-framework

Sorry for the confusion.  Please let me know if you have any questions.

2019-05-17 14:04 UTC, arciisine commented on src/app/app.component.ts
> +        fromEvent(new EventSource('/neon/services/dataset/listen'), 'message').subscribe((time) => this.dataAvailableDashboard());
Okay, will move

2019-05-17 16:36 UTC, arciisine commented on src/app/app.component.ts
> +        fromEvent(new EventSource('/neon/services/dataset/listen'), 'message').subscribe((time) => this.dataAvailableDashboard());
Moved and updated

2019-05-21 21:26 UTC, ThomasSchellenbergNextCentury commented
@rartiss55 You'll need to change the `neon-framework` dependency in your `package.json` file to pull from the feature branch until it's merged-in:
```
"neon-framework": "git+https://github.com/NextCenturyCorporation/neon-framework.git#THOR-1183-Receive-Streaming-Messages-In-UI"
```

2019-05-21 21:30 UTC, ThomasSchellenbergNextCentury commented
@arciisine I'm getting an error on `npm start`:
```
ERROR in src/app/app.component.ts(194,63): error TS2339: Property 'DATASET_UPDATED' does not exist on type 'typeof channels'.
```
However, I can verify that `DATASET_UPDATED` is in my `channels` in `node_modules/neon-framework/dist/neon.js.`  Any ideas?

2019-05-21 21:34 UTC, arciisine commented
> @arciisine I'm getting an error on `npm start`:
> 
> ```
> ERROR in src/app/app.component.ts(194,63): error TS2339: Property 'DATASET_UPDATED' does not exist on type 'typeof channels'.
> ```
> 
> However, I can verify that `DATASET_UPDATED` is in my `channels` in `node_modules/neon-framework/dist/neon.js.` Any ideas?
This is tied to a specific neon-framework version as changes were needed there to facilitate streaming.  I pull the framework repo locally and change the npm dependency to "file://../neon-framework" (assuming it's a sibling folder).

2019-05-22 15:05 UTC, rartiss55 commented
@arciisine For PRs like this in the future, it'd be good to list out the different things needed to run it in the description (i.e. "please run this against xyz branch in neon-server and update neon-framework dependency to abc").

2019-05-22 15:30 UTC, ThomasSchellenbergNextCentury commented
@arciisine The badge (red dot) on the notification icon is always there, even when `updatedData` is false.  What's up with that?

2019-05-22 15:50 UTC, ThomasSchellenbergNextCentury commented
So, the `refreshDashboard` function wasn't working the way any sane person would expect it to work (edit: 
 I mean, before you touched anything -- I'm not blaming you!), so I pushed a fix for that.  Now all of the visualizations will requery whenever you hit that notification button.

2019-05-22 17:02 UTC, rartiss55 requested changes
Looks good -- I'll second Thomas' comment though about the notification badge. That shouldn't be red if updatedData is false.

2019-05-22 17:11 UTC, arciisine commented
> @arciisine For PRs like this in the future, it'd be good to list out the different things needed to run it in the description (i.e. "please run this against xyz branch in neon-server and update neon-framework dependency to abc").

Will do, wasn't sure how to communicate these things, so makes sense.

2019-05-22 17:59 UTC, arciisine commented
Yeah, that shouldn't be firing on load. Will fix.

On Wed, May 22, 2019 at 1:07 PM rartiss55 <notifications@github.com> wrote:

> *@rartiss55* requested changes on this pull request.
>
> Looks good -- I'll second Thomas' comment though about the notification
> badge. That shouldn't be red if updatedData is false.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NextCenturyCorporation/neon-dash-internal/pull/211?email_source=notifications&email_token=AAJUULYR57MIUTWSYZN4EGDPWV4WBA5CNFSM4HNQNWU2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOBZM4AVY#pullrequestreview-240762967>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJUUL4X6CMYS5EKADBKQ6LPWV4WBANCNFSM4HNQNWUQ>
> .
>

2019-05-22 19:42 UTC, rartiss55 approved these changes

2019-05-24 12:06 UTC, merged