Merge LORELEI into AIDA / VERDI
NextCenturyCorporation/neon-dash pull request #217
Opened 2019-05-21 13:56 UTC by ThomasSchellenbergNextCentury

Hey folks, could you please make sure that the AIDA dashboards / datasets work with the LORELEI team's changes?

As a reminder, you can use the same ES 2 and Neon Server WAR that you've been using.

Overall, the changes include the config overhaul (with the new config files), the new widget option ("gear") menus, the filtering changes, and a variety of other minor enhancements and bug fixes.

I've verified that all of the AIDA-specific filtering works (I think!), but I encourage you to double-check me :)

If you'd prefer, we can wait to merge this until the new filter badges have been implemented (which should be ready within the next few days).

Thanks!

2019-05-21 22:05 UTC, gitnordt requested changes

2019-05-21 22:05 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.html
The taxonomy leaf nodes should not be displayed with checkboxes since they are not intended to be filterable. It looks like you removed the columnName from the description in the taxonomy node objects. This has caused the check to for displaying checkboxes to become invalid. Please change node.data.description to be node.data.description.columnName in the html.

2019-05-21 22:28 UTC, gitnordt requested changes

2019-05-21 22:28 UTC, gitnordt commented on src/app/components/document-viewer/document-viewer.component.html
> +            </button>
This may be a separate ticket, but I noticed this issue while testing. The thumbnail grid paging and filtering are not working together properly. When you click on a document on the first page of the thumbnail grid, the filter is created and the document that was clicked is displayed. If you go to another page and perform the same action, the filtered document is not displayed. 

I think it's because that document is still showing up on the first page when we are on the next page if that makes any sense. I remember fixing this issue a while back when Charlotte was interning ([https://nextcentury.atlassian.net/browse/AIDA-278](AIDA-278)), but the fix was removed most likely during a merge.

2019-05-21 22:40 UTC, gitnordt commented
I noticed that the legend in the map does not have a switch to turn legendFiltering off in the map like in the network graph. This would be a great addition. Can we put in a ticket to add that option to the map legend? 

Also, I agree that it would be a good idea to add the new badges to this PR.

2019-05-22 14:46 UTC, ThomasSchellenbergNextCentury commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.html
Will do!

2019-05-22 14:50 UTC, ThomasSchellenbergNextCentury commented
@snorpet "This would be a great addition" I think you meant to say that it would be a LEGENDARY addition!  I created the ticket:  https://nextcentury.atlassian.net/browse/NEON-43

2019-05-22 15:09 UTC, ThomasSchellenbergNextCentury commented on src/app/components/document-viewer/document-viewer.component.html
> +            </button>
Done!

2019-05-23 17:10 UTC, gitnordt requested changes

2019-05-23 17:10 UTC, gitnordt commented on src/app/components/timeline/timeline.component.ts
> +                (value, index, array) => array.indexOf(value) === index);
The new filterField code does not seem to be working. On the TA2 Network Dashboard, when I select a document in the right-side component, I expect the document component as well as the timeline to filter. The timeline is no longer filtering when a document is clicked.

2019-05-23 17:16 UTC, gitnordt commented on src/app/components/document-viewer/document-viewer.component.html
> +            </button>
The document is now showing up as expected, but when the filter is removed, I am taken to the first page again. Please add the code back in to keep track of the current page. It is not ideal for the user to click through 5 pages, used the filter, and then have to click through the pages again and try to find where they left off.

2019-05-23 17:39 UTC, gitnordt commented on src/app/components/timeline/timeline.component.ts
> +                (value, index, array) => array.indexOf(value) === index);
Wait, I'm wrong. I don't believe that it is the filterField causing this issue. Document/Timeline filtering works as expected in TA2 Events and Map Dashboard. We may need to dig a little bit to find out why this isn't working.

2019-05-24 17:48 UTC, ThomasSchellenbergNextCentury commented on src/app/components/document-viewer/document-viewer.component.html
> +            </button>
Stacey, I don't take your code away from you, I just break your code!  :)

Anyway, I can totally understand the need for this behavior.  It should be fixed now.  Sorry for breaking it in the first place!

2019-05-24 17:49 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/timeline.component.ts
> +                (value, index, array) => array.indexOf(value) === index);
I saw it too.  I think I've fixed the issue.

2019-05-29 15:45 UTC, gitnordt approved these changes

2019-05-29 20:00 UTC, bdpham approved these changes

2019-05-29 20:29 UTC, closed without merging