Thor taxonomy optimization
NextCenturyCorporation/neon-dash pull request #221
Opened 2019-05-24 21:06 UTC by arciisine

This is the initial pass at the taxonomy overhaul, and was hoping to see if you could kick the tires a bit and let me know if anything seems off.  The counts are still a little different so I'm assuming there is still some stuff to discuss.

2019-05-25 19:34 UTC, gitnordt requested changes
Yaaay! The taxonomy load performance is much improved. I just had a few suggestions to correct some of the functionality/features and a couple comments.

2019-05-25 19:34 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +            };
Your valueField logic does not appear to be working. When this field is set, you should see a final leaf layer that only consists of values. Its styling is completely different. The values are surrounded by a border and do not have checkboxes because they are listed for discovery purposes and not intended to be filterable. 
![valuesScreenshot](https://user-images.githubusercontent.com/6887586/58373440-774e7680-7efc-11e9-8f28-de0fddda18c1.png)

2019-05-25 19:34 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.html
> +            <mat-tree-node *matTreeNodeDef="let node" matTreeNodeToggle>
In all honesty, I definitely like the styling of the Angular Tree better than the Material Tree. The checkboxes are a little too vibrant for my taste. I also do understand the need to minimize the Neon code base. I think ultimately this is Sophie and Thomas' call.

2019-05-25 19:34 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.html
> +                                [class.node-content-wrapper-focused]="node.isFocused">
It looks like the double click feature that used to open and close the tree levels is being overridden, I'm assuming by the toggle filtering action that Thomas put in. It was a nice to have, but not a necessity so feel free to remove the dblclick code since it is no longer being used.

2019-05-25 19:34 UTC, gitnordt commented on src/app/components/taxonomy-viewer/taxonomy-viewer.component.ts
> +                if (child.externalId) {
The counts appear to be inaccurate because duplicate nodeIds(kbids) are being counted. Unfortunately, the nodeIds are listed multiple times in the database to represent each link to the node. You may want to add the check back in to track nodeIds and ensure that they are not duplicated/counted multiple times. You may also need a check for the name and lineage to ensure you are counting the correct child in the tree. You can reference line 482 of the previous code. Or in hindsight, I guess you could also use the ElasticSearch _id instead since it is unique, but you would still need to collect the nodeIds for filtering purposes.

2019-05-30 17:53 UTC, arciisine commented
Closing in favor of https://github.com/NextCenturyCorporation/neon-dash-internal/pull/224, code will remain, but PR is dead for the time being

2019-05-30 17:53 UTC, closed without merging