Adding Jenkins Pipeline Support
NextCenturyCorporation/neon-dash pull request #309
Opened 2019-07-29 12:57 UTC by arciisine

Adds Jenkins Pipeline support and removes support for WAR building. 

Additionally reorganized the top level to better group resources.

Reworked environment to not need scripts to be run first.

2019-07-31 15:20 UTC, ThomasSchellenbergNextCentury commented on package.json
> +    "start": "npx ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --port 4200",
@arciisine It looked like we were previously using the `ng.sh` script to build and run the application with a bigger `max_old_space_size`.  Now it looks like you're using the default `ng` command.  Is the `max_old_space_size` no longer important?

2019-07-31 15:22 UTC, ThomasSchellenbergNextCentury commented on package.json
> +    "build-prod": "npx ng build --prod --base-href=/$npm_config_base --deploy-url=/$npm_config_base",
@arciisine I see that the post-build action of zipping the files from the `dist` folder into a WAR file has been removed.  Are we no longer expecting to support the deployment of the application as a WAR file?

2019-07-31 15:22 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/timeline.component.spec.ts
> +    xit('transformVisualizationQueryResults does return expected data without id and filter fields', () => {
@arciisine Why are these two tests disabled?  It breaks the linter.  Edit:  I'm not asking solely because of the linter; if the unit tests are broken, we may want to fix them.

2019-07-31 15:50 UTC, ThomasSchellenbergNextCentury commented on e2e/bin/convert.sh
> +DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
@arciisine Is this script actually used anywhere?

2019-07-31 15:52 UTC, ThomasSchellenbergNextCentury commented
@arciisine I'm getting failures on the end-to-end tests:

```
    ✗ widget should have settings
      - Failed: No element found using locator: by.buttonText("settings")
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:814:27
          at ManagedPromise.invokeCallback_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2927:27
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:668:7
          at processTicksAndRejections (internal/process/task_queues.js:89:5)Error
          at ElementArrayFinder.applyAction_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:459:27)
          at ElementArrayFinder.<computed> [as click] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:91:29)
          at ElementFinder.<computed> [as click] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:831:22)
          at Object.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:91:55)
          at step (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:32:23)
          at Object.next (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:13:53)
          at fulfilled (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:4:58)
          at processTicksAndRejections (internal/process/task_queues.js:89:5)
      From: Task: Run it("widget should have settings") in control flow
          at UserContext.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/jasminewd2/index.js:94:19)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/jasminewd2/index.js:64:48
          at ControlFlow.emit (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/events.js:62:21)
          at ControlFlow.shutdown_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2674:10)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2599:53
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2728:9
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:668:7
          at processTicksAndRejections (internal/process/task_queues.js:89:5)
      From asynchronous test: 
      Error
          at Suite.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:86:5)
          at Object.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:18:1)
          at Module._compile (internal/modules/cjs/loader.js:774:30)
          at Module.m._compile (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/ts-node-2/src/index.ts:473:23)
          at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
          at Object.require.extensions.<computed> [as .ts] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/ts-node-2/src/index.ts:476:12)
          at Module.load (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
          at Function.Module._load (internal/modules/cjs/loader.js:556:12)
          at Module.require (internal/modules/cjs/loader.js:681:19)
          at require (internal/modules/cjs/helpers.js:16:16)
          at Array.forEach (<anonymous>)
          at Function.promise (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:682:9)
          at _fulfilled (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:834:54)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:863:30
          at Promise.promise.promiseDispatch (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:796:13)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:556:49
          at runSingle (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:137:13)
          at flush (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:125:13)
          at processTicksAndRejections (internal/process/task_queues.js:82:9)
    ✗ should be able to remove visualizations
      - NoSuchElementError: No element found using locator: By(css selector, .visualization-border>div)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:814:27
          at ManagedPromise.invokeCallback_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2927:27
          at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:668:7
          at processTicksAndRejections (internal/process/task_queues.js:89:5)Error
          at ElementArrayFinder.applyAction_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:459:27)
          at ElementArrayFinder.<computed> [as getId] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:91:29)
          at ElementFinder.<computed> [as getId] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:831:22)
          at ActionSequence.mouseMove (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/actions.js:151:44)
          at Object.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:140:33)
          at step (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:32:23)
          at Object.next (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:13:53)
          at fulfilled (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:4:58)
          at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

2019-07-31 17:45 UTC, ThomasSchellenbergNextCentury requested changes

2019-07-31 17:45 UTC, ThomasSchellenbergNextCentury commented on Dockerfile
> +  proxy_pass http://neon-server-service;\n\
@arciisine Sorry, I know we talked about this already, but please remind me:  where is the name `neon-server-service` defined?  Is it in the AWS config?

2019-07-31 17:45 UTC, ThomasSchellenbergNextCentury commented on Jenkinsfile
> +          passwordVariable: 'AWS_SECRET_ACCESS_KEY'
@arciisine Are the variables like `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `BRANCH_NAME` defined by Jenkins?  Or by somewhere else that I'm missing?

2019-07-31 17:45 UTC, ThomasSchellenbergNextCentury commented on terraform/static-site.tf
> +  default = "ec2-52-201-222-156.compute-1.amazonaws.com"
@arciisine If we ever needed to deploy this system somewhere else, we'd need to change all of the specific AWS hostnames here, right?

2019-07-31 17:49 UTC, arciisine commented on package.json
> +    "start": "npx ng serve --proxy-config proxy.conf.json  --host 0.0.0.0 --port 4200",
I don't know, I will take a look

2019-07-31 17:49 UTC, arciisine commented on package.json
> +    "build-prod": "npx ng build --prod --base-href=/$npm_config_base --deploy-url=/$npm_config_base",
That was the intention of the branch, to remove WAR support and only build docker files

2019-07-31 17:50 UTC, arciisine commented on src/app/components/timeline/timeline.component.spec.ts
> +    xit('transformVisualizationQueryResults does return expected data without id and filter fields', () => {
Yeah, so this was for testing purposes as these tests were breaking, but not due to changes on my side.  I figured we could resolve that in the merge, or that someone may have already fixed them.

2019-07-31 17:51 UTC, arciisine commented on e2e/bin/convert.sh
> +DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
This is the script for converting the selenium ide tests into proper protractor spec tests.

2019-07-31 17:52 UTC, arciisine commented on Dockerfile
> +  proxy_pass http://neon-server-service;\n\
It's the name of the kubernetes service or it could be the name of the container in a docker compose file.

2019-07-31 17:52 UTC, arciisine commented on Jenkinsfile
> +          passwordVariable: 'AWS_SECRET_ACCESS_KEY'
AWS_* are standard AWS environment variables that we populate from username/password settings.  BRANCH_NAME is provided by jenkins

2019-07-31 17:53 UTC, arciisine commented on terraform/static-site.tf
> +  default = "ec2-52-201-222-156.compute-1.amazonaws.com"
For the static site, yes.  Theoretically this would turn into kubernetes deployments, but that can be discussed.

2019-07-31 17:53 UTC, arciisine commented
> @arciisine I'm getting failures on the end-to-end tests:
> 
> ```
>     ✗ widget should have settings
>       - Failed: No element found using locator: by.buttonText("settings")
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:814:27
>           at ManagedPromise.invokeCallback_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:1376:14)
>           at TaskQueue.execute_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3084:14)
>           at TaskQueue.executeNext_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3067:27)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2927:27
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:668:7
>           at processTicksAndRejections (internal/process/task_queues.js:89:5)Error
>           at ElementArrayFinder.applyAction_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:459:27)
>           at ElementArrayFinder.<computed> [as click] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:91:29)
>           at ElementFinder.<computed> [as click] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:831:22)
>           at Object.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:91:55)
>           at step (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:32:23)
>           at Object.next (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:13:53)
>           at fulfilled (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:4:58)
>           at processTicksAndRejections (internal/process/task_queues.js:89:5)
>       From: Task: Run it("widget should have settings") in control flow
>           at UserContext.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/jasminewd2/index.js:94:19)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/jasminewd2/index.js:64:48
>           at ControlFlow.emit (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/events.js:62:21)
>           at ControlFlow.shutdown_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2674:10)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2599:53
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2728:9
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:668:7
>           at processTicksAndRejections (internal/process/task_queues.js:89:5)
>       From asynchronous test: 
>       Error
>           at Suite.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:86:5)
>           at Object.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:18:1)
>           at Module._compile (internal/modules/cjs/loader.js:774:30)
>           at Module.m._compile (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/ts-node-2/src/index.ts:473:23)
>           at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
>           at Object.require.extensions.<computed> [as .ts] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/ts-node-2/src/index.ts:476:12)
>           at Module.load (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
>           at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>           at Module.require (internal/modules/cjs/loader.js:681:19)
>           at require (internal/modules/cjs/helpers.js:16:16)
>           at Array.forEach (<anonymous>)
>           at Function.promise (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:682:9)
>           at _fulfilled (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:834:54)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:863:30
>           at Promise.promise.promiseDispatch (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:796:13)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:556:49
>           at runSingle (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:137:13)
>           at flush (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/q/q.js:125:13)
>           at processTicksAndRejections (internal/process/task_queues.js:82:9)
>     ✗ should be able to remove visualizations
>       - NoSuchElementError: No element found using locator: By(css selector, .visualization-border>div)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:814:27
>           at ManagedPromise.invokeCallback_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:1376:14)
>           at TaskQueue.execute_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3084:14)
>           at TaskQueue.executeNext_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:3067:27)
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:2927:27
>           at /home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/promise.js:668:7
>           at processTicksAndRejections (internal/process/task_queues.js:89:5)Error
>           at ElementArrayFinder.applyAction_ (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:459:27)
>           at ElementArrayFinder.<computed> [as getId] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:91:29)
>           at ElementFinder.<computed> [as getId] (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/protractor/built/element.js:831:22)
>           at ActionSequence.mouseMove (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/node_modules/selenium-webdriver/lib/actions.js:151:44)
>           at Object.<anonymous> (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:140:33)
>           at step (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:32:23)
>           at Object.next (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:13:53)
>           at fulfilled (/home/HQ/tschellenberg/Development/darpa/neon/dash-internal/e2e/app.e2e-spec.ts:4:58)
>           at processTicksAndRejections (internal/process/task_queues.js:89:5)
> ```

Not sure what is happening here, I'm assuming the tests are still passing in the jenkins pipeline.

2019-08-06 17:06 UTC, ThomasSchellenbergNextCentury approved these changes

2019-08-06 17:06 UTC, merged