bug fix: download attributes fix for firefox
NextCenturyCorporation/neon-dash pull request #349
Opened 2019-10-08 11:42 UTC by aamduka

2019-10-08 15:42 UTC, chrislong commented on src/app/components/export-control/export-control.component.ts
> +        var url = URL.createObjectURL(new Blob([queryResults.data], {type:"application/octet-stream"}));
`application/octet-stream`? Isn't this text data?

2019-10-08 15:42 UTC, chrislong requested changes
Just wondering about the MIME type.

2019-10-09 12:59 UTC, aamduka commented on src/app/components/export-control/export-control.component.ts
> +        var url = URL.createObjectURL(new Blob([queryResults.data], {type:"application/octet-stream"}));
Chris,

I was thinking some browsers might try to display the content instead of prompting user to download when they see "text/plain" MIME type. With application/octet-stream no browser would attempt to open it. But all the browsers on my machine didn't try to open it when using "text/plain" so I went ahead with "text/plain" hoping older browsers would not attempt to open the file.

2019-10-09 14:16 UTC, chrislong approved these changes

2019-10-09 14:23 UTC, merged