Aida 254
NextCenturyCorporation/neon-dash pull request #60
Opened 2018-09-25 18:37 UTC by bdpham

Added filtering capabilities to network graph

2018-09-26 15:43 UTC, gitnordt requested changes

2018-09-26 15:43 UTC, gitnordt commented on src/app/components/network-graph/network-graph.component.html
> +                    [matTooltip]="'Delete Filter ' + getFilterText(filter)" (click)="removeLocalFilterFromLocalAndNeon(filter, true, false)">
I would suggest adding the multiFilterOperator to the mat-sidenav so that it can be switch from "and" to "or" without having to change the config file.

2018-09-26 15:43 UTC, gitnordt commented on src/app/components/network-graph/network-graph.component.ts
> +                        clause = neon.query.where(myFilter.field, '=', myFilter.value);
Was there a reason that you chose this method of defining the "and" clause as opposed to using _neon.query.and.apply(neon.query, clauses)_? I believe that they both return the same results.

2018-09-26 15:43 UTC, gitnordt commented on src/app/components/network-graph/network-graph.component.ts
> +            this.addNeonFilter(true, myFilter, clause);
Why are we displaying the "or" filters as one comma-delimited string and the "and" filters as multiple individual strings? Shouldn't they be consistent?

2018-09-26 17:43 UTC, bdpham commented on src/app/components/network-graph/network-graph.component.ts
> +                        clause = neon.query.where(myFilter.field, '=', myFilter.value);
By creating multiple filters, neon defaults to "and". This way, we are able to close/remove certain clauses from the "and" filter. If we use the neon.query.and.apply(neon.query, clauses) method, it puts all clauses into one filter, which prevents the user from closing out certain clauses.

2018-09-26 17:45 UTC, bdpham commented on src/app/components/network-graph/network-graph.component.ts
> +            this.addNeonFilter(true, myFilter, clause);
Because of the way the neon middleware works, in order to have "or" functionality on multiple clauses, we must use this the neon.query.or.apply(neon.query, clauses) method. In order to have multiple different independent clauses that can be removed individually, we must implement a method in the front end that can recalculate the different clauses to create the or filter for neon. This is confusing, I know.

2018-09-26 17:45 UTC, bdpham commented on src/app/components/network-graph/network-graph.component.html
> +                    [matTooltip]="'Delete Filter ' + getFilterText(filter)" (click)="removeLocalFilterFromLocalAndNeon(filter, true, false)">
Will do.

2018-09-26 18:09 UTC, gitnordt approved these changes

2018-09-26 18:10 UTC, merged

2018-09-27 13:39 UTC, ThomasSchellenbergNextCentury commented on src/app/components/network-graph/network-graph.component.html
> +
Hey @bdpham sorry I'm late to the review.  It would be nice if you also added a toggle for the "filterable" option as well.

2018-09-27 13:40 UTC, ThomasSchellenbergNextCentury commented on src/app/components/network-graph/network-graph.component.ts
> +            // let nodeSelected = this.onSelect.bind(this);
@bdpham When you get the chance, please remove this commented-out code.

2018-09-27 15:07 UTC, bdpham commented on src/app/components/network-graph/network-graph.component.html
> +
This will be a backlog item.

2018-09-27 15:08 UTC, bdpham commented on src/app/components/network-graph/network-graph.component.ts
> +            // let nodeSelected = this.onSelect.bind(this);
@snorpet volunteered to remove it on her next PR.