Aida 378
NextCenturyCorporation/neon-dash pull request #66
Opened 2018-10-12 14:03 UTC by bdpham

added missing code from merge

2018-10-12 15:38 UTC, ThomasSchellenbergNextCentury requested changes
You've got an issue with your filter-adding behavior.  Otherwise everything looks fine.

2018-10-12 15:38 UTC, ThomasSchellenbergNextCentury commented on src/app/components/network-graph/network-graph.component.ts
> +            for (let filterField of selectedNode.filterFields) {
Calling addNeonFilter within a loop (by calling addFilter on lines 1105 and 1111) will cause errors due to race conditions.  You need to call addNeonFilter once on your first filter, wait for a successful response from the backend, and then call addNeonFilter again on your second filter.  Right now, you're calling addNeonFilter in rapid-fire succession, which sends all the add-filter requests to the backend without waiting for the backend to process the requests and thus may get the backend filter state out-of-whack.

The addNeonFilter function has a 4th argument for a callback function.  You need to move the loop behavior to a separate function and then, on your first call to addNeonFilter supply a callback that calls your new function to add the next filter.  Let me know if you have questions or I'm not being clear.

2018-10-12 15:39 UTC, bdpham commented on src/app/components/network-graph/network-graph.component.ts
> +            for (let filterField of selectedNode.filterFields) {
Ahhh that makes sense. I will fix that. Thanks.

2018-10-12 18:07 UTC, gitnordt requested changes
I noticed that if you double-click on a node in the Network Graph to filter and then click on a hypothesis, the closeable filter in the network graph disappears as if the filter was removed. However if you look at the filter tray, the filter still exists. 
![screenshot from 2018-10-12 13-56-07](https://user-images.githubusercontent.com/6887586/46886182-16b87080-ce28-11e8-8b40-83c0bcd805f1.png)

2018-11-01 14:09 UTC, bdpham commented
@snorpet I will put in a different issue for the bug that you found.

2018-11-01 19:46 UTC, ThomasSchellenbergNextCentury approved these changes

2018-11-01 19:48 UTC, merged

2018-11-01 20:07 UTC, gitnordt reviewed
That's acceptable. Let me know the bug number for the filtering issue.