THOR 517 Data table column reorderable
NextCenturyCorporation/neon-dash pull request #68
Opened 2018-10-17 14:56 UTC by Konnoke

2018-10-17 19:31 UTC, rartiss55 submitted a review, later dismissed

2018-10-17 19:42 UTC, ThomasSchellenbergNextCentury requested changes

2018-10-17 19:42 UTC, ThomasSchellenbergNextCentury commented on src/app/components/data-table/data-table.component.ts
> +        this.reorderable = this.injector.get('reorderable', true);
Please add reorderable to subGetBindings.

2018-10-17 19:42 UTC, ThomasSchellenbergNextCentury commented on src/app/components/data-table/data-table.component.html
> +                [reorderable]="options.reorderable"
Please add a mat-button-toggle-group for reorderable to toggle true or false.

2018-10-17 19:57 UTC, Konnoke commented on src/app/components/data-table/data-table.component.ts
> +        this.reorderable = this.injector.get('reorderable', true);
Added in the latest commit

2018-10-17 19:57 UTC, Konnoke commented on src/app/components/data-table/data-table.component.html
> +                [reorderable]="options.reorderable"
Added in the latest commit

2018-10-18 13:57 UTC, ThomasSchellenbergNextCentury approved these changes

2018-10-18 13:57 UTC, merged