Aida 99 multiple filter fields and relations
NextCenturyCorporation/neon-dash pull request #7
Opened 2018-03-14 15:20 UTC by bdpham

Data-table component can have multiple filter fields. Added relations to simple-verdi config.

2018-03-14 18:35 UTC, eaciv requested changes
Just a few questions and a request for comments

2018-03-14 18:35 UTC, eaciv commented on src/app/components/data-table/data-table.component.ts
> +        // We do it this way instead of using splice() because we have to replace filter array
If splice is the right way to do this, you should still use it. Then you can create a copy of the array with either array.slice() or [...array].

2018-03-14 18:35 UTC, eaciv commented on src/app/components/base-neon-component/base-neon.component.ts
> +    findFieldObjects(bindingKey: string, mappingKey?: string): FieldMetaData[] {
Did you have to add this to base-neon or is this part of a Lorelei merge?

2018-03-14 18:35 UTC, eaciv commented on src/app/components/data-table/data-table.component.ts
> +            let object = this.active.rawData.filter((obj) =>
Please add a couple comments to this section so it's easy to tell at a glance what logic we're using

2018-03-14 18:35 UTC, eaciv commented on src/app/config/config.simple_verdi.json
> +				{"members": [
Did you ever get a good answer from Daniel about why "members" is required?

2018-03-14 18:43 UTC, bdpham commented on src/app/components/data-table/data-table.component.ts
> +        // We do it this way instead of using splice() because we have to replace filter array
Ok. That makes sense. I pulled this piece from a different component.

2018-03-14 18:44 UTC, bdpham commented on src/app/components/base-neon-component/base-neon.component.ts
> +    findFieldObjects(bindingKey: string, mappingKey?: string): FieldMetaData[] {
I added it because I need an array of FieldMetaData to be returned. I'll look into possibly combining it with findFieldObject method.

2018-03-14 18:45 UTC, bdpham commented on src/app/components/data-table/data-table.component.ts
> +            let object = this.active.rawData.filter((obj) =>
Will do.

2018-03-14 18:45 UTC, bdpham commented on src/app/config/config.simple_verdi.json
> +				{"members": [
No. I never got around to asking him.

2018-03-15 13:39 UTC, eaciv approved these changes

2018-03-15 13:39 UTC, merged