Fixed Theme Style Infrastructure
NextCenturyCorporation/neon-dash pull request #80
Opened 2018-10-29 19:09 UTC by ThomasSchellenbergNextCentury

I fixed how we use themes in the Neon dashboard by switching from SASS (compiled) variables to CSS (dynamic) variables.

I moved the Neon theme CSS class from each individual widget to just the app-root element.

I updated the teal theme to match the current draft from UX (THOR-851) though I anticipate minor adjustments in the future.

I added stubs for green theme and dark theme.

Please let me know if you have any questions.  Thanks!

2018-10-29 19:11 UTC, ThomasSchellenbergNextCentury commented on package.json
> +    "postinstall": "npm run remove-postcss-custom-properties"
I had to remove postcss-custom-properties because it gave me superfluous warnings when using CSS variables (that are obviously not relevant, since they work).  It's included in the Angular CLI but is only needed to support legacy browsers.  Here's where I found the workaround:

https://github.com/angular/angular-cli/issues/7991#issuecomment-346765757

2018-10-29 19:13 UTC, ThomasSchellenbergNextCentury commented on src/app/components/timeline/timeline.component.scss
> +$tooltip-background: rgba(255,255,255,0.9);
These were moved from the old _custom-theming.scss file (now removed).

2018-10-29 19:29 UTC, ThomasSchellenbergNextCentury commented on src/styles.scss
> +}
https://nextcentury.atlassian.net/browse/THOR-898

2018-10-29 19:33 UTC, ThomasSchellenbergNextCentury commented on src/themes/neon-teal-theme.scss
> +    --color-text-main: #333333;
The @ include styles the angular material components while the CSS variables style our custom Neon Dash components.

2018-10-30 13:06 UTC, Konnoke approved these changes

2018-11-01 18:20 UTC, gitnordt requested changes

2018-11-01 18:20 UTC, gitnordt commented on src/app/services/themes.service.ts
>      }];
Does it make more sense to create THEMES as an object so that you do not have to reference the theme by number? Accessing the theme by name will eliminate having to know/lookup the theme ids.

    public static THEMES = {
        TEAL : {id: 'neon-teal', name: 'Teal'},
        GREEN: {id: 'neon-green', name: 'Green'},
        DARK : {id: 'neon-dark', name: 'Dark'}
    };

    private currentTheme = ThemesService.THEMES.TEAL;

You would still be able to use this.themesService.getCurrentTheme().id and can use the variable to set the current theme in dashboard-options.component.ts.

2018-11-01 18:20 UTC, gitnordt commented on src/themes/neon-teal-theme.scss
> +    --color-text-main: #333333;
Somehow with the theme additions, the mat-autocomplete background-color is unset. This is causing the Query Bar menu to look transparent. We may need to add a background-color to the mat-autocomplete element in the Query Bar scss to alleviate the problem.
![transparentmenu](https://user-images.githubusercontent.com/6887586/47870055-f3f1fa00-ddde-11e8-9892-fc7ed1765648.png)

2018-11-01 18:20 UTC, gitnordt commented on src/app/components/dashboard-options/dashboard-options.component.ts
> +        currentTheme: 'neon-teal',
When I change the current theme, I don't see a difference in the interface for AIDA. Is this working for other projects?

2018-11-01 18:20 UTC, gitnordt commented on src/styles.scss
> +@import 'themes/neon-teal-theme';
When running the project, I'm getting several warnings pertaining to styles.scss themes imports. Are you seeing this on your end and is this something that can be addressed?
![stylewarnings](https://user-images.githubusercontent.com/6887586/47871066-6b288d80-dde1-11e8-9c90-a770eb906d85.png)

2018-11-01 19:28 UTC, Konnoke commented on src/styles.scss
> +@import 'themes/neon-teal-theme';
Removing your current node module and npm install should fix that issue

2018-11-01 20:14 UTC, ThomasSchellenbergNextCentury commented on src/app/components/dashboard-options/dashboard-options.component.ts
> +        currentTheme: 'neon-teal',
The green and dark themes are not implemented yet, just stubbed out (copies of the teal theme).  I'll remove the options from the settings for now.

2018-11-01 20:15 UTC, ThomasSchellenbergNextCentury commented on src/app/services/themes.service.ts
>      }];
Great idea!

2018-11-02 14:41 UTC, ThomasSchellenbergNextCentury commented on src/themes/neon-teal-theme.scss
> +    --color-text-main: #333333;
Great catch!  Some of the overlay elements have proven problematic with the new theme changes.  I just pushed a commit that fixed it now, though.

2018-11-07 23:26 UTC, gitnordt approved these changes

2018-11-07 23:27 UTC, merged